# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a59cb3fd7f9a07e9dd9873698b2a390d1a03bda7dadb41c2530fd90e02ebbecff4d98337d86d3a00154c771288e39f111f8161fe72d584d64b2db36810e51e6c

test:
  secret_key_base: 61e6c2290e6c4d46e0651a7a520d928b2828d18035467a36ca6afb507f9850f38d308be93799fbfc5bac102ca030b8ac930aa44c7b014bc3129a1ac1170a9e30

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
