Company.create!([
  {name: "Xero"},
  {name: "Trade Me"},
  {name: "Solnet"},
  {name: "Stripe the Web"},
  {name: "Resene Group"},
  {name: "SilverStripe"},
  {name: "OrbitRemit Global"},
  {name: "Kiwibank"},
  {name: "Mindscape"},
  {name: "Regen Ltd"},
  {name: "Publons"},
  {name: "Embrium"},
  {name: "HashBang"},
  {name: "Optimal Workshop"},
  {name: "Collect"},
  {name: "3Months"},
  {name: "Department of International Affairs"},
  {name: "NZRS"}
])
Interview.create!([
  {company: "Xero"},
  {company: "Trade Me"},
  {company: "Solnet"},
  {company: "Stripe the Web"},
  {company: "Resene Group"},
  {company: "SilverStripe"},
  {company: "OrbitRemit Global"},
  {company: "Kiwibank"},
  {company: "Mindscape"},
  {company: "Regen Ltd"},
  {company: "Publons"},
  {company: "Embrium"},
  {company: "HashBang"},
  {company: "Optimal Workshop"},
  {company: "Collect"},
  {company: "3Months"},
  {company: "Department of International Affairs"},
  {company: "NZRS"}
])
Question.create!([
  {question: "Part-time work after summer", interview: "Xero"},
  {question: "Languages/ Framworks?", interview: "Xero"},
  {question: "Part-time work after summer", interview: "Trade Me"},
  {question: "Languages/ Framworks?", interview: "Trade Me"},
  {question: "Part-time work after summer", interview: "Solnet"},
  {question: "Languages/ Framworks?", interview: "Solnet"},
  {question: "Part-time work after summer", interview: "Stripe the Web"},
  {question: "Languages/ Framworks?", interview: "Stripe the Web"},
  {question: "Part-time work after summer", interview: "Resene Group"},
  {question: "Languages/ Framworks?", interview: "Resene Group"},
  {question: "Part-time work after summer", interview: "SilverStripe"},
  {question: "Languages/ Framworks?", interview: "SilverStripe"},
  {question: "Part-time work after summer", interview: "OrbitRemit Global"},
  {question: "Languages/ Framworks?", interview: "OrbitRemit Global"},
  {question: "Part-time work after summer", interview: "Kiwibank"},
  {question: "Languages/ Framworks?", interview: "Kiwibank"},
  {question: "Part-time work after summer", interview: "Mindscape"},
  {question: "Languages/ Framworks?", interview: "Mindscape"},
  {question: "Part-time work after summer", interview: "Regen Ltd"},
  {question: "Languages/ Framworks?", interview: "Regen Ltd"},
  {question: "Part-time work after summer", interview: "Publons"},
  {question: "Languages/ Framworks?", interview: "Publons"},
  {question: "Part-time work after summer", interview: "Embrium"},
  {question: "Languages/ Framworks?", interview: "Embrium"},
  {question: "Part-time work after summer", interview: "HashBang"},
  {question: "Languages/ Framworks?", interview: "HashBang"},
  {question: "Part-time work after summer", interview: "Optimal Workshop"},
  {question: "Languages/ Framworks?", interview: "Optimal Workshop"},
  {question: "Part-time work after summer", interview: "Collect"},
  {question: "Languages/ Framworks?", interview: "Collect"},
  {question: "Part-time work after summer", interview: "3Months"},
  {question: "Languages/ Framworks?", interview: "3Months"},
  {question: "Part-time work after summer", interview: "Department of International Affairs"},
  {question: "Languages/ Framworks?", interview: "Department of International Affairs"},
  {question: "Part-time work after summer", interview: "NZRS"},
  {question: "Languages/ Framworks?", interview: "NZRS"}
])
